### ISSUE TITLE
感觉那个PDF不是很清楚啊

### ISSUE THREAD

**Issue by meteormatt** [bxiaopeng/AndroidStudio#1]
很多页上都有乱码的痕迹.
难道是我的PDF软件的问题?
![snap1](https://f.cloud.github.com/assets/424475/2134525/45cb7182-92e7-11e3-86f5-fe631fd170b7.png)

**Comment by bxiaopeng** [comment]
Me too

**Comment by bxiaopeng** [comment]
Me too

**Comment by bxiaopeng** [comment]
Welcome you !

**Comment by bxiaopeng** [comment]
Me too
