### ISSUE TITLE
how to get or make the newest green version android studio 

### ISSUE THREAD

**Issue by lion117** [bxiaopeng/AndroidStudio#2]
i had get tired of install android studio  and download relative SDK , that was disgusting as you know chinese network . 
i had wasted too much time on how to build up android development environment  there are at least 3 computer need to rebuild up . .. too many traps for chinese developers because of GFW. i had noticed that the newest android is 1.00 stable ,type . but  the version you contributed was 0.8  . 
so my question how did you make or get the green android studio ? 
appreciate

**Comment by SEALiu** [comment]
VPN

**Comment by Catouse** [comment]
http://help.honx.in/posts/view/32854/

**Comment by bxiaopeng** [comment]
使用VPN下载,或者我下载好发给你.
