### ISSUE TITLE
第一章 1.1.3 表格内容错误

### ISSUE THREAD

**Issue by dxg74120** [bxiaopeng/AndroidStudio#21]
linux中Gnome和Kde属于桌面环境而ubuntu是发行版本名称，文中描述有问题，“gnome,kde或ubuntu，推荐使用ubuntu。”不应该使用这句话来描述。

**Comment by bxiaopeng** [comment]
多谢指出,已攺为: Ubuntu/Fedora/Debian 
GNU C Library (glibc) 2.15 或更高版本
