### ISSUE TITLE
求教这个错误怎么修，我是在2.1preview版上

### ISSUE THREAD

**Issue by MichaelSZM** [bxiaopeng/AndroidStudio#5]
从网上下载的代码，一半以上都报错：Error:Unable to start the daemon process: could not reserve enough space for object heap.
Please assign more memory to Gradle in the project's gradle.properties file.
For example, the following line, in the gradle.properties file, sets the maximum Java heap size to 1,024 MB:
<em>org.gradle.jvmargs=-Xmx1024m</em>
<a href="http://www.gradle.org/docs/current/userguide/build_environment.html">Read Gradle's configuration guide</a><br><a href="http://docs.oracle.com/javase/7/docs/technotes/guides/vm/gc-ergonomics.html">Read about Java's heap size</a>
照着改完（在gradle.properties中加上这句org.gradle.jvmargs=-Xmx1024m），没起什么作用啊

**Comment by bxiaopeng** [comment]
呀呀呀呀,你都用上2.1啦, 建议哈,2.0都还没有release, 2.1肯定更不稳定啦. 所以尝鲜可以,千万别用它做项目. 你最好安装两个AS。

回到问题上,报空间不足，除了上面修攺方法,还可以这样攺:
![01](https://cloud.githubusercontent.com/assets/3722923/14045109/1dc05db8-f2d2-11e5-813a-91c56ac7c857.png)

路径： AS启动界面 --> Configure --> Preferences --> Compiler

你试试！！

**Comment by MichaelSZM** [comment]
请教：这个错能解吗？
Error:(19, 0) Gradle DSL method not found: 'android()'
Possible causes:<ul><li>The project 'FamiliarRecyclerView' may be using a version of Gradle that does not contain the method.
<a href="open.wrapper.file">Open Gradle wrapper file</a></li><li>The build file may be missing a Gradle plugin.
<a href="apply.gradle.plugin">Apply Gradle plugin</a></li>

**Comment by bxiaopeng** [comment]
请确认下是否是缺少插件
