### ISSUE TITLE
百度试读2.13.1图贴错了

### ISSUE THREAD

**Issue by yfsyyy** [bxiaopeng/AndroidStudio#50]
2.13.1第四张图贴的不对吧，我看了windows mac版的2.1.2和windows的2.0，那张图都没有左边的那栏，在Vector Asset里有找到这张图。还有2.13.1前面的三张图为什么会是黑色的呢？

**Comment by bxiaopeng** [comment]
你好，多谢提醒，我用的是android studio 2.2 , 难道有bug?  等我更新的2.2 第四版再看一眼。

**Comment by bxiaopeng** [comment]
确认过了，确实是黑的，就是这样的效果。
