### ISSUE TITLE
运行chapter12\BasicUnitAndroidTest 出现这个问题怎么解决

### ISSUE THREAD

**Issue by ycyangchun** [bxiaopeng/AndroidStudio#51]
"C:\Program Files\Java\jdk1.8.0_40\bin\java" -ea -Didea.launcher.port=7532 "-Didea.launcher.bin.path=C:\Program Files\Android\Android Studio2.0\bin" -Didea.junit.sm_runner -Dfile.encoding=UTF-8 -classpath "C:\Program Files\Android\Android Studio2.0\lib\idea_rt.jar;C:\Program Files\Android\Android Studio2.0\plugins\junit\lib\junit-rt.jar;C:\mySoft\sdk2\platforms\android-23\data\res;C:\myGitlab\AndroidStudio\chapter12\BasicUnitAndroidTest\app\build\intermediates\classes\debug;C:\Users\Administrator\.gradle\caches\modules-2\files-2.1\org.hamcrest\hamcrest-core\1.3\42a25dc3219429f0e5d060061f71acb49bf010a0\hamcrest-core-1.3.jar;C:\Users\Administrator\.gradle\caches\modules-2\files-2.1\junit\junit\4.12\2973d150c0dc1fefe998f834810d68f278ea58ec\junit-4.12.jar;C:\myGitlab\AndroidStudio\chapter12\BasicUnitAndroidTest\app\build\intermediates\sourceFolderJavaResources\test\debug;C:\myGitlab\AndroidStudio\chapter12\BasicUnitAndroidTest\app\build\intermediates\sourceFolderJavaResources\debug;C:\myGitlab\AndroidStudio\chapter12\BasicUnitAndroidTest\build\generated\mockable-android-23.jar" com.intellij.rt.execution.application.AppMain com.intellij.rt.execution.junit.JUnitStarter -ideVersion5 com.example.android.testing.unittesting.basicunitandroidtest.LogHistoryAndroidUnitTest

Process finished with exit code 1
Class not found: "com.example.android.testing.unittesting.basicunitandroidtest.LogHistoryAndroidUnitTest"Empty test suite.

**Comment by bxiaopeng** [comment]
你好，请问你是怎么运行的？按照书上写的方法吗？
