### ISSUE TITLE
关于第14章的共享GitHub遇到的问题

### ISSUE THREAD

**Issue by paceyxio** [bxiaopeng/AndroidStudio#53]
我按照14.5的步骤提示，在share project on github的对话框中填写完库的描述后点击share，软件提示 Failed to create GitHub Repository Can't create repository: MyApplication Moved Permanently.
我尝试了几个工程还尝试新建了一个工程也都共享不了。
百度也没找到解决办法，所以希望您能抽空帮个忙。
![20160823195504](https://cloud.githubusercontent.com/assets/20932794/17897322/5d2e01fa-6986-11e6-8a4e-bfac239a701e.png)
![screenshot_2016-08-23-22-58-22](https://cloud.githubusercontent.com/assets/20932794/17897324/5d751342-6986-11e6-8b81-30e0feaa4ba0.png)

**Comment by bxiaopeng** [comment]
确认已经登录Github：
偏好设置 --> Version Control --> GitHub --> 已输入用户名和密码，点[Test]提示连接成功。

**Comment by paceyxio** [comment]
我是按照书上的步骤test也显示链接成功，填写完description后点击share就出现错误
![qq 20160824235419](https://cloud.githubusercontent.com/assets/20932794/17938808/2c2de82a-6a5a-11e6-89dc-0d2c5c150dad.png)
![qq 20160825002140](https://cloud.githubusercontent.com/assets/20932794/17938806/2a9754f6-6a5a-11e6-91a3-8cd38d5f0a0a.png)
![qq 20160825002154](https://cloud.githubusercontent.com/assets/20932794/17938807/2ac02bce-6a5a-11e6-80b9-24a8afa1692b.png)

**Comment by bxiaopeng** [comment]
刚我又试了一遍，是可以分享成功的。 加我QQ 782670627.

**Comment by paceyxio** [comment]
申请加好友了，我QQ头像和这个Github一样的。
