### ISSUE TITLE
第10章重构排版问题

### ISSUE THREAD

**Issue by lingjie2098** [bxiaopeng/AndroidStudio#54]
第10章重构，老毕应该是没插入图片，像以下这样的地方很多，影响阅读体验。恳请改进。
![default](https://cloud.githubusercontent.com/assets/15832370/18340953/4deeb06c-75da-11e6-9c1e-9730397fe185.PNG)
# **附带请教老毕一个问题：Android Studio中如何自动格式化，我现在都是Ctrl + Alt + L手动。Eclipse有这个功能，以至于我只要保存，它就会自动帮你格式化。**

**Comment by bxiaopeng** [comment]
多谢反馈，这个反馈太重要了，第10章不是缺少图片，而是所有的代码都没有显示。这个是百度阅读的BUG，所以代码我需要重新上传。

另外保存时自动格式化的问题，我没有找到解决方案。

**Comment by bxiaopeng** [comment]
已补全。
