### ISSUE TITLE
第16章图文不匹配问题

### ISSUE THREAD

**Issue by lingjie2098** [bxiaopeng/AndroidStudio#55]
第三部分《3.9.管理Android SDK平台》图文不匹配：在“如果想删除已安装的包，就取消对应API的勾选：”这句话之后，约摸3张图片不匹配。虽然是小问题，但是改进会好一点。

**Comment by bxiaopeng** [comment]
已修正，确实是图片传错了。 感谢反馈，还请持续反馈。
