### ISSUE TITLE
多处文字错误

### ISSUE THREAD

**Issue by hdfywxn** [bxiaopeng/AndroidStudio#56]
![1](https://cloud.githubusercontent.com/assets/11352147/21747183/1eef5850-d59a-11e6-92a3-4784bc9d7aa0.PNG)

![d](https://cloud.githubusercontent.com/assets/11352147/21747184/1ef0e22e-d59a-11e6-9c25-92537195d5cb.PNG)
#
![default](https://cloud.githubusercontent.com/assets/11352147/21747185/1f143634-d59a-11e6-8f12-6d89e5b585f5.PNG)
#

**Comment by bxiaopeng** [comment]
已修正，多谢反馈。
