### ISSUE TITLE
请教AndroidStudio里检索依赖库

### ISSUE THREAD

**Issue by VeiZhang** [bxiaopeng/AndroidStudio#57]
步骤：File->Project Structure->Dependencies->Library Dependency；有时候可以检索出比较有名的依赖库，如：RxJava等，但是我通过[Bintray][Bintray]上传自己打包的依赖库，却不能找到？我想请教一下AndroidStudio里的检索的服务器是哪里？怎么样才能检索出自己的依赖库呢？

![androidstudio](https://cloud.githubusercontent.com/assets/19425616/24451532/ccfd9f78-14b1-11e7-9614-f88ad2b9ea73.png)

[Bintray]:https://bintray.com

**Comment by cxldada** [comment]
![image](https://user-images.githubusercontent.com/11706518/30689785-907fe97a-9ef4-11e7-85c9-31b77654c262.png)

**Comment by VeiZhang** [comment]
@cxldada 谢谢，上传的服务器不对才会导致没检索到
